Our project can be open with anaconda's JupyterLab.
The find.peaks may cause weired bugs, please change the distance to some other value, excute it, and then change back to the original value.
//change the distance here when it says something out of range: peaks, _ = find_peaks(filtered_signal, distance=100)
